import {Inter} from "next/font/google"
import localFont from 'next/font/local'
import './globals.css'

const inter = Inter({
  weight : ['400','600','900'],
  preload: false,
  variable : '--font-inter'
})

const pricedownBl = localFont({
  src : './pricedownbl.ttf',
  variable : '--font-PricedownBl',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${pricedownBl.variable} font-sans`}>{children}</body>
    </html>
  )
}
